import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import MobileBottomNav from '@/app/components/layout/MobileBottomNav';
import React from 'react';
import HeaderToolbar from '@/app/components/layout/HeaderToolbar';
import SessionProvider from './session-provider';
import { getServerSession } from 'next-auth';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} antialiased dark`}>
        <SessionProvider session={session}>
          <main className="flex flex-col gap-y-4 font-sans h-screen p-4 pb-16">
            <HeaderToolbar />
            {children}
          </main>
          <MobileBottomNav />
        </SessionProvider>
      </body>
    </html>
  );
}
